# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10

  - name: 研究方向
    url: research
    weight: 20

  - name: 最新动态
    url: post
    weight: 50

  - name: 团队成员
    url: people
    weight: 30

  - name: 论文成果
    url: publication
    weight: 40

  - name: 加入我们
    url: contact
    weight: 60
